Django/project/getcare/website/getcareapp/urls.py
from django.urls import path

from . import views

app_name = 'getcare'

urlpatterns = [
    path('',views.login, name='login'),  
    path('register/',views.register, name='register'),
    path('login/',views.login, name='login'),
    path('<str:currentKey>/index/<str:classTask>', views.index, name='index'),
    path('<str:currentKey>/newtask/', views.newTask, name='newtask'),
    path('<str:currentKey>/viewtask/<int:task_id>', views.viewtask, name='viewtask'),
    path('<str:currentKey>/info/', views.info, name='info'),
    path('<str:currentKey>/viewnote/<int:note_id>',views.viewnote, name='viewnote'),
    path('<str:currentKey>/newnote/', views.newnote, name='newnote'),
    path('<str:currentKey>/calendar/<str:classType>', views.calendar, name='calendar'),
    path('<str:currentKey>/uploadcsv/', views.uploadCSV, name='uploadcsv'),

    path('<str:currentKey>/viewrelation/', views.viewRelations, name='viewRelations'),
    path('<str:currentKey>/viewrelation_carer/', views.viewRelations, name='viewRelationsCarer'),
    path('<str:currentKey>/viewrelation_provider/', views.viewRelations, name='viewRelationsProviders'),

    path('<str:currentKey>/viewrelation/', views.addRelation, name='addRelation'),
    path('<str:currentKey>/viewrelation/', views.removeRelation, name='removeRelation'),

    path('<str:currentKey>/viewtask/<int:task_id>', views.addNote, name='addnote'),

    path('<str:currentKey>/results/', views.results, name='results'),
    path('<str:currentKey>/newtaskforme/', views.newTaskForMe, name='newtaskforme'),
    path('<str:currentKey>/newtodo/', views.newTodo, name='newtodo'),
    path('<str:currentKey>/todolist/<str:classTodo>', views.todolist, name='todolist'),
    path('<str:currentKey>/viewtodo/<int:todo_id>', views.viewtodo, name='viewtodo'),

    path('<str:currentKey>/templatelist/<str:classTemplate>', views.templatelist, name='templatelist'),
    path('<str:currentKey>/newtemplate/', views.newTemplate, name='newtemplate'),
    path('<str:currentKey>/viewtemplate/<int:template_id>', views.viewtemplate, name='viewtemplate'),

    path('<str:currentKey>/templatelistforme/<str:classTemplate>', views.templatelistforme, name='templatelistforme'),
    path('<str:currentKey>/newtemplateforme/', views.newTemplateForMe, name='newtemplateforme'),
    path('<str:currentKey>/viewtemplateforme/<int:template_id>', views.viewtemplateforme, name='viewtemplateforme'),





]

Django/project/getcare/website/website/urls.py
from django.contrib import admin
from django.urls import path,include
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('getcare/',include('getcareapp.urls')),
    path('', lambda request: redirect('getcare/', permanent=False))
]

Django/project/getcare/website/getcareapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from .models import *
from django.utils import timezone
from django.urls import reverse
import random
import string
from django.core.exceptions import ObjectDoesNotExist
from django.core.files.storage import FileSystemStorage
from datetime import datetime, timedelta, date
import calendar as libCalendar
import json
from django.core import serializers

def getCarerbyKey(currentKey):
    try:
        return Carer.objects.get(key=currentKey)
    except ObjectDoesNotExist:
        return False


def getUserbyKey(currentKey):
    try:
        return User.objects.get(key=currentKey)
    except ObjectDoesNotExist:
        return False


def getProviderbyKey(currentKey):
    try:
        return Provider.objects.get(key=currentKey)
    except ObjectDoesNotExist:
        return False


def findingUser(currentKey):
    current_user = getUserbyKey(currentKey)
    userType = "USER"
    if (current_user == False):
        current_user = getCarerbyKey(currentKey)
        userType = "CARER"
    if (current_user == False):
        current_user = getProviderbyKey(currentKey)
        userType = "PROVIDER"
    if (current_user == False):
        userType = "NONE"
    return current_user, userType


def addAssociatedCarers(currentKey, carers):
    currentUser, userType = findingUser(currentKey)
    for carer in carers.iterator():
        print(carer.relation_code)
        addRelation(currentKey, "carer", carer.relation_code)


def findSeniors(currentKey):  # As provider or carer
    currentUser, userType = findingUser(currentKey)
    if userType == "PROVIDER":
        seniors = ProviderSeniorRelationship.objects.filter(provider=currentUser)
        return seniors
    if userType == "CARER":
        seniors = CarerSeniorRelationship.objects.filter(carer=currentUser)
        return seniors


def findCarers(currentKey):
    currentUser, userType = findingUser(currentKey)
    carers = ProviderCarerRelationship.objects.filter(provider=currentUser)
    return carers


def findProviders(currentKey):
    currentUser, userType = findingUser(currentKey)
    if userType == "USER":
        providers = ProviderSeniorRelationship.objects.filter(senior=currentUser)
        return providers
    if userType == "CARER":
        providers = ProviderCarerRelationship.objects.filter(carer=currentUser)
        return providers


def findCarersToAdd(currentKey, seniorRelationCode):  # only call this when usertype is provider
    currentUser, userType = findingUser(currentKey)
    addedSenior = User.objects.filter(relation_code=seniorRelationCode).first()
    carers = Carer.objects.none()
    carers = CarerSeniorRelationship.objects.filter(senior=addedSenior)
    carersFromCarerTable = Carer.objects.none()
    for carer in carers.iterator():
        carersFromCarerTable |= Carer.objects.filter(id=carer.id)
    return carersFromCarerTable


def findUserTypeByEmail(currentEmail):
    current_user = getUserbyEmail(currentEmail)
    userType = "USER"
    if (current_user == False):
        current_user = getCarerbyEmail(currentEmail)
        userType = "CARER"
    if (current_user == False):
        current_user = getProviderbyEmail(currentEmail)
        userType = "PROVIDER"
    if (current_user == False):
        userType = "NONE"
    return userType


def findingTasks(currentUser, userType):
    user_tasks = ""
    if userType == "USER":
        user_tasks = Tasks.objects.filter(user=currentUser)
    elif userType == "CARER":
        user_tasks = Tasks.objects.filter(carer=currentUser)
    elif userType == "PROVIDER":
        user_tasks = Tasks.objects.filter(provider=currentUser)
    return user_tasks

def findingTodos(currentUser, userType):
    user_todos = ""
    if userType == "USER":
        user_todos = Todos.objects.filter(user=currentUser)
    elif userType == "CARER":
        user_todos = Todos.objects.filter(carer=currentUser)
    elif userType == "PROVIDER":
        user_todos = Todos.objects.filter(provider=currentUser)
    return user_todos

def findingNotes(currentTask):  # finds all notes associated with a given task
    print(Notes.objects.filter(task=currentTask))
    return Notes.objects.filter(task=currentTask)


def addNote(currentKey, comment, task_id):
    currentTask = Tasks.objects.filter(id=task_id).first()
    currentUser, userType = findingUser(currentKey)
    if userType == "USER":
        Notes.objects.create(detail=comment, create_date=timezone.now(), user=currentUser, task=currentTask)
    if userType == "PROVIDER":
        Notes.objects.create(detail=comment, create_date=timezone.now(), provider=currentUser, task=currentTask)
    if userType == "CARER":
        Notes.objects.create(detail=comment, create_date=timezone.now(), carer=currentUser, task=currentTask)


def changeNote(currentKey, comment, task_id):
    currentTask = Tasks.objects.filter(id=task_id).first()
    currentUser, userType = findingUser(currentKey)
    notes = Notes.objects.filter(task=currentTask)
    if userType == "USER":
        note = notes.filter(senior=currentUser).delete()
        Notes.objects.create(detail=comment, create_date=timezone.now(), user=currentUser, task=currentTask)
    if userType == "PROVIDER":
        note = notes.filter(provider=currentUser).delete()
        Notes.objects.create(detail=comment, create_date=timezone.now(), provider=currentUser, task=currentTask)
    if userType == "CARER":
        notes.filter(carer=currentUser).delete()
        Notes.objects.create(detail=comment, create_date=timezone.now(), carer=currentUser, task=currentTask)


def findingRelations(currentUser, userType):
    relations = [None] * 2
    if userType == "USER":
        relations[0] = ProviderSeniorRelationship.objects.filter(senior=currentUser)
        relations[1] = CarerSeniorRelationship.objects.filter(senior=currentUser)
    elif userType == "CARER":
        relations[0] = ProviderCarerRelationship.objects.filter(carer=currentUser)
        relations[1] = CarerSeniorRelationship.objects.filter(carer=currentUser)
    elif userType == "PROVIDER":
        relations[0] = ProviderCarerRelationship.objects.filter(provider=currentUser)
        relations[1] = ProviderSeniorRelationship.objects.filter(provider=currentUser)
    return relations


def getUserbyEmail(currentEmail):
    try:
        return User.objects.get(email=currentEmail)
    except ObjectDoesNotExist:
        return False


def getCarerbyEmail(currentEmail):
    try:
        return Carer.objects.get(email=currentEmail)
    except ObjectDoesNotExist:
        return False


def getProviderbyEmail(currentEmail):
    try:
        return Provider.objects.get(email=currentEmail)
    except ObjectDoesNotExist:
        return False


def getTask(taskID, userKey):
    current_user, userType = findingUser(userKey)

    if userType == "USER":
        user_tasks = Tasks.objects.filter(user=current_user)
    elif userType == "CARER":
        user_tasks = Tasks.objects.filter(carer=current_user)
    elif userType == "PROVIDER":
        user_tasks = Tasks.objects.filter(provider=current_user)

    for user_task in user_tasks:
        if user_task.id == taskID:
            return Tasks.objects.get(id=taskID)
    return False


# def getNote(noteID, userKey):
#    current_user, userType = findingUser(userKey)

#    if userType == "USER":
#        user_notes = Notes.objects.filter(user=current_user)
#    elif userType == "CARER":
#        user_notes = Notes.objects.filter(carer=current_user)
#    elif userType == "PROVIDER":
#        user_notes = Notes.objects.filter(provider=current_user)

#    for user_note in user_notes:
#        if user_note.id == noteID:
#            return Notes.objects.get(id=noteID)
#    return False


def register(request):
    if request.method == "GET":
        return render(request, 'GetCare/register.html')

    # random the key
    seed = string.ascii_letters + string.digits
    key = random.sample(seed, 62)
    all_user = User.objects.all()
    i = 0
    key_list = []
    for i in range(len(all_user)):
        key_list.append(all_user[i].key)
    while key in key_list:
        key = random.sample(seed, 62)

    current_user = getUserbyEmail(request.POST['email'])
    if current_user:
        return HttpResponse(r"The email has been registered as a senior account")
    current_user = getCarerbyEmail(request.POST['email'])
    if current_user:
        return HttpResponse(r"The email has been registered as a carer account")
    current_user = getProviderbyEmail(request.POST['email'])
    if current_user:
        return HttpResponse(r"The email has been registered as a provider account")

    if request.POST['role'] == 'senior':
        if request.POST['relationCode'] == '':
            return HttpResponse("Please enter your relation code")
        try:
            mycarer = Carer.objects.get(relation_code=request.POST['relationCode'])
        except ObjectDoesNotExist:
            return HttpResponse("We cannot find this relation code in our system")

        if mycarer.User:
            return HttpResponse("The relation code has been registered")

        User.objects.create(firstName=request.POST['FirstName'],
                            lastName=request.POST['LastName'],
                            email=request.POST['email'],
                            password=request.POST['password'],
                            gender=request.POST['gender'],
                            phone=request.POST['phone'],
                            key="".join(key),
                            carer=mycarer,
                            )
        mycarer.User = User.objects.get(email=request.POST['email'])
        mycarer.save()
        return HttpResponse(r"Successful.<br><a href=\getcare\login> Login </a>")
    elif request.POST['role'] == 'carer':
        relationCode = random.randint(0, 999999)
        Carer.objects.create(firstName=request.POST['FirstName'],

Django/project/getcare/website/getcareapp/templates/GetCare/templatelistforme.html
<!-- 
{% if user %}
    {{Message}}<br>
{% endif %}
<br>
<a href="{% url 'getcare:login'  %}">Log off</a>
<p>Task List</p>
<a href="{% url 'getcare:newtask' user.key %}">Add a New Task</a>
<br><br>
{% if Tasks %}

    {% for task in Tasks %}
        <a href="{% url 'getcare:viewtask' user.key task.id %}">{{ task.title }} -- {{task.start_date}}</a><br>
    {% endfor %}

{% else %}
    <p>No Tasks are available.</p>
{% endif %}
{% if Notes %}

    {% for note in Notes %}
        <a href="{% url 'getcare:viewnote' user.key note.id %}">{{ note.title }} -- {{note.start_date}}</a><br>
    {% endfor %}

{% else %}
    <p>No Notes are available.</p>
{% endif %} -->
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body {
  font-family: Arial, Helvetica, sans-serif;
}

/* Bar */
.header {
  overflow: hidden;
  background-color: #ffffff;
  height: 95px;
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
}

.header a {
  float: left;
  font-size: 16px;
  color: white;
  text-align: center;
  text-decoration: none;
}

.navbar {
  overflow: hidden;
  background-color: rgb(152, 108, 235);
  margin-top: 95px;
}

.navbar a {
  float: left;
  font-size: 16px;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

.navbar a:hover, .dropdown:hover .dropbtn {
  background-color: #ddd;
  color: black;
}

.dropdown {
  float: left;
  overflow: hidden;
}

.dropdown .dropbtn {
  font-size: 16px;  
  border: none;
  outline: none;
  color: rgb(255, 255, 255);
  padding: 14px 16px;
  background-color: inherit;
  font-family: inherit;
  margin: 0;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f9f9f9;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  float: none;
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
  text-align: left;
}

.dropdown-content a:hover {
  background-color: #ddd;
}

.dropdown:hover .dropdown-content {
  display: block;
}
.search {
  overflow: hidden;

}
.search input[type=text] {
  float:right;
  padding: 6px;
  margin-top: 8px;
  margin-right: 120px;
  border: none;
  font-size: 17px;
}
.profile{
  float: right;
  background-color: rgb(0, 0, 0);
  color: rgb(255, 255, 255);
  border: none;
  font-family: Arial, Helvetica, sans-serif;
  text-align: center;
  text-decoration: none;
  font-size: 20px;
  cursor: pointer;
  padding: 10px 28px;
  margin-right: 30px;
  margin-top: 37px;
}
.profile:hover {
  background-color: rgb(152, 108, 235);
  color: rgb(255, 255, 255);
  font-weight: lighter;
}
.logoff{
  float: right;
  border: none;
  font-family: Arial, Helvetica, sans-serif;
  padding: 10px 15px;
  text-align: center;
  text-decoration: none;
  font-size: 20px;
  cursor: pointer;
  margin-right: 135px;
  margin-top: 37px;
}
.logoff a{
  background-color: #ffffff;
  color: #000000;
}
.logoff a:hover {
  background-color: #ffffff;
  color: rgb(152, 108, 235);
  font-weight: normal;
}


@media screen and (max-width: 600px) {
  .search a, .search input[type=text] {
    float: right;
    display: block;
    text-align: left;
    width: 100%;
    margin-right: 50px;
    padding: 14px;
  }
  
  .search input[type=text] {
    border: 1px solid #ccc;  
  }
}

/* content */
.button {
  border: none;
  background-color: rgb(152, 108, 235);
  color: #fff;
  font-family: Arial, Helvetica, sans-serif;
  text-align: center;
  text-decoration: none;
  font-size: 20px;
  cursor: pointer;
  margin: auto;
  padding: 10px 15px;
  position: absolute;
  right: 160px;
  top: 170px;
}
.button a{
  background-color: rgb(152, 108, 235);
  color: #fff;
}
.button a:hover{
  background-color: rgb(152, 108, 235);
  color: rgb(0, 0, 0);
  font-weight: normal;
}

.buttons {
  border: none;
  cursor: pointer;
  margin: auto;
  position: absolute;
  right: 160px;
  top: 225px;
}

.button-type{
  border: none;
  background-color: white;
  color: rgb(152, 108, 235);
  cursor: pointer;
  margin-left: 5px;
  padding: 6px 11px;
  outline: 1px solid rgb(152, 108, 235);
  font-family: Arial, Helvetica, sans-serif;
  text-align: center;
  text-decoration: none;
  font-size: 13px;
  font-weight: normal;
  text-transform: uppercase;
}

.button-type:hover{
  background-color: rgb(152, 108, 235);
  color: white;
}

table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  margin: 150px;
  width: 80%;

}

table td {
  border-top: 0;
  border-right: 2px solid black;
  border-bottom: 2px solid black;
  border-left: 0;
}

table tr:last-child td{
  border-bottom: 0;
}

table tr td:last-child{
  border-right: 0;
}

table tr td:first-child{
  width:420px;
}


td, th {
  border:2px solid #000000;
  text-align: center;
  padding: 0px;
}

td a { 
   display: block; 
   position:static;
   border: 1px solid transparent;
   margin-bottom: -22px;
   padding: 15px; 
}

a:hover{
  background: rgb(152, 108, 235);
  color: black;
  font-weight: bold;
}

tr:nth-child(even) {
  background-color: #e9f5ef;}

</style>
</head>
<body>


<div class="header">
  <a href="{% url 'getcare:index' user.key 'INCOMPLETED' %}"><img src="{% static 'getcareapp/getcare2.png' %}" id="logo" height="60px" width="290px" style="position:absolute; left:125px; top:20px"/></a>
  <a href="{% url 'getcare:index' user.key 'INCOMPLETED' %}"><img src="{% static 'getcareapp/LOGO_01.png' %}" id="logo" height="22px" width="49px" style="position:absolute; left:420px; top:54px"/></a>
  
  <div class="logoff">
    <a href="{% url 'getcare:login' %}">Log Off</a>
  </div> 

  <div class="profile">
    <a href="{% url 'getcare:info' user.key %}"style="font-weight: lighter;">My Profile</a>
  </div> 

</div>

<div class="navbar">
  
  <div class="dropdown">
    <button class="dropbtn"> Tasks 
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="{% url 'getcare:index' user.key 'ALL' %}">All</a>
      <a href="{% url 'getcare:index' user.key 'COMPLETED' %}">Completed</a>
      <a href="{% url 'getcare:index' user.key 'INCOMPLETED' %}">Incomplete</a>
      
    </div>
  </div> 

  <div class="dropdown">
    <button class="dropbtn">Calendar 
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
        <a href="{% url 'getcare:calendar' user.key 'week' %}">Week View</a>
        <a href="{% url 'getcare:calendar' user.key 'month' %}">Month View</a>

    </div>
  </div> 

  <div class="dropdown">
    <button class="dropbtn">Provider 
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="{% url 'getcare:index' user.key 'ALL' %}">All</a>
      <a href="{% url 'getcare:index' user.key 'CAREPLAN' %}">Care Plan</a>
      <a href="{% url 'getcare:index' user.key 'MEDICATION' %}">Medication</a>
      <a href="{% url 'getcare:index' user.key 'COMMUNICATION' %}">Communication</a>
      <a href="{% url 'getcare:index' user.key 'ACTIVITY' %}">Activity</a>
      <a href="{% url 'getcare:index' user.key 'MEAL' %}">Meal</a>
      <a href="{% url 'getcare:index' user.key 'OTHER' %}">Other</a>
    </div>
  </div> 
  
  <div class="dropdown">
    <button class="dropbtn">Relations 
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="{% url 'getcare:viewRelations' user.key %}">Relations</a>
    </div>
  </div> 

  <div class="dropdown">
    <button class="dropbtn">Task Template 
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="{% url 'getcare:templatelist' user.key 'ALL' %}">Task Template</a>
      <a href="{% url 'getcare:templatelistforme' user.key 'ALL' %}">Task For Me Template</a>
    </div>
  </div> 

  <div class="dropdown">
    <button class="dropbtn">To-do List 
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="{% url 'getcare:todolist' user.key 'ALL' %}">All</a>
      <a href="{% url 'getcare:todolist' user.key 'COMPLETED' %}">Completed</a>
      <a href="{% url 'getcare:todolist' user.key 'INCOMPLETED' %}">Incomplete</a>
      <a href="{% url 'getcare:todolist' user.key 'CARE' %}">Care Plan</a>
      <a href="{% url 'getcare:todolist' user.key 'MEDICATION' %}">Medication</a>
      <a href="{% url 'getcare:todolist' user.key 'COMMUNICATION' %}">Communication</a>
      <a href="{% url 'getcare:todolist' user.key 'ACTIVITY' %}">Activity</a>
      <a href="{% url 'getcare:todolist' user.key 'MEAL' %}">Meal</a>
      <a href="{% url 'getcare:todolist' user.key 'OTHER' %}">Other</a>
    </div>
  </div> 

  <form action="{% url 'getcare:results' user.key %}" class="search" method="get" >
    {% csrf_token %}
    <input id="search" name="search" type="text" placeholder="Search...">
    <input type="submit" hidden="true">
  </form>

</div>
 <!-- content -->


    <button class="button" >
      <a href="{% url 'getcare:newtemplateforme' user.key %}" style="text-decoration: none;">+ New Task Template For Me</a>
    </button>

    <div class='buttons'>
      <button id="button-all" class="button-type">All</button>
      <button id="button-care" class="button-type">Care Plan</button>
      <button id="button-medi" class="button-type">Medication</button>
      <button id="button-comm" class="button-type">Communication</button>
      <button id="button-acti" class="button-type">Activity</button>
      <button id="button-meal" class="button-type">Meal</button>
      <button id="button-other" class="button-type">Other</button>
    </div>

    <table style= "margin-top:130px"  >
      <tr>
        <th style="text-align:center;padding:10px;">Template</th>
        <th style="text-align:center; width:20%">Senior</th>
        <th style="text-align:center; width:20%">Type</th>
        <!-- <th style="text-align:center">Deadline</th> -->
      </tr>
      {% if Templates %}
        {% for template in Templates %}
          <tr>
          <td style="text-align:center"> 
            <label for="task1"  style="font-size: 18px;"> 
            <a href="{% url 'getcare:viewtemplateforme' user.key template.id %}" style="text-decoration: none;cursor: pointer;">{{ template.name }}</a><br> </label>
          </td>
          <td style="text-align:center">
            <p for="person" >{{ template.user.firstName}} {{ template.user.lastName}}</p>
          </td>
          <td style="text-align:center">
            <p for="person" >{{ template.classTask }}</p>
          </td>
          <!-- <td style="text-align:center"> -->
            <!-- <p for="timestamp" class="time"> {{task.start_date}} </p> -->
          <!-- </td>     -->
          </tr>
        {% endfor %}
      {% else %}
          <p>No Templates are available.</p>
      {% endif %}

    </table>
    <script type="text/javascript">
      var btnIDs = ['button-all', 'button-care', 'button-medi', 'button-comm', 'button-acti', 'button-meal', 'button-other'];
      var names = ['ALL', 'CARE', 'MEDICATION', 'COMMUNICATION', 'ACTIVITY', 'MEAL', 'OTHER'];
      var map = new Map();
      for (let i=0; i<names.length; i++) {
        map.set(names[i], btnIDs[i]);
      }
      for (let btnid of btnIDs) {
        document.getElementById(btnid).onclick = selectButton;
      }

      var pn = window.location.pathname;
      var type = pn.substring(pn.lastIndexOf('/')+1);
      document.getElementById(map.get(type)).style.backgroundColor = 'rgb(152, 108, 235)';
      document.getElementById(map.get(type)).style.color = '#fff';
    
      function selectButton(){
      for (let [key, value] of map.entries()) {
        if (value == this.id) {
          var string = pn.substring(0, pn.lastIndexOf('/')+1) + key;
          window.location = string;
          break;
        }
      }
    }

    // function selectButton(){
    //   switch (this.id) {
    //     case 'button-all':
    //       window.location="{% url 'getcare:templatelistforme' user.key 'ALL' %}";
    //       break;
    //     case 'button-care':
    //       window.location="{% url 'getcare:templatelistforme' user.key 'CARE' %}";
    //       break;
    //     case 'button-medi':
    //       window.location="{% url 'getcare:templatelistforme' user.key 'MEDICATION' %}";
    //       break;
    //     case 'button-comm':
    //       window.location="{% url 'getcare:templatelistforme' user.key 'COMMUNICATION' %}";
    //       break;
    //     case 'button-acti':
    //       window.location="{% url 'getcare:templatelistforme' user.key 'ACTIVITY' %}";
    //       break;
    //     case 'button-meal':
    //       window.location="{% url 'getcare:templatelistforme' user.key 'MEAL' %}";
    //       break;
    //     case 'button-other':
    //       window.location="{% url 'getcare:templatelistforme' user.key 'OTHER' %}";
    //       break;
    //   }
    // }
    </script>
</body>
</html>